// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: links.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createShortLink = `-- name: CreateShortLink :one
INSERT INTO shortly(id, user_id, short_link, long_link)
VALUES($1, $2, $3, $4)
RETURNING id, user_id, short_link, long_link, click_count, created_at, updated_at
`

type CreateShortLinkParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ShortLink string    `json:"short_link"`
	LongLink  string    `json:"long_link"`
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (Shortly, error) {
	row := q.db.QueryRowContext(ctx, createShortLink,
		arg.ID,
		arg.UserID,
		arg.ShortLink,
		arg.LongLink,
	)
	var i Shortly
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortLink,
		&i.LongLink,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM shortly WHERE short_link = $1
`

func (q *Queries) DeleteLink(ctx context.Context, shortLink string) error {
	_, err := q.db.ExecContext(ctx, deleteLink, shortLink)
	return err
}

const getLinks = `-- name: GetLinks :many
SELECT id, user_id, short_link, long_link, click_count, created_at, updated_at FROM shortly
ORDER BY created_at DESC
`

func (q *Queries) GetLinks(ctx context.Context) ([]Shortly, error) {
	rows, err := q.db.QueryContext(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shortly
	for rows.Next() {
		var i Shortly
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortLink,
			&i.LongLink,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLongLink = `-- name: GetLongLink :one
SELECT id, user_id, short_link, long_link, click_count, created_at, updated_at FROM shortly
WHERE short_link = $1
LIMIT 1
`

func (q *Queries) GetLongLink(ctx context.Context, shortLink string) (Shortly, error) {
	row := q.db.QueryRowContext(ctx, getLongLink, shortLink)
	var i Shortly
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortLink,
		&i.LongLink,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLinks = `-- name: GetUserLinks :many
SELECT id, user_id, short_link, long_link, click_count, created_at, updated_at FROM shortly
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserLinks(ctx context.Context, userID uuid.UUID) ([]Shortly, error) {
	rows, err := q.db.QueryContext(ctx, getUserLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shortly
	for rows.Next() {
		var i Shortly
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortLink,
			&i.LongLink,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE shortly
SET click_count = click_count + 1, updated_at = NOW()
WHERE short_link = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, shortLink string) error {
	_, err := q.db.ExecContext(ctx, incrementClickCount, shortLink)
	return err
}
