// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Shortly struct {
	ID        uuid.UUID `json:"id"`
	ShortLink string    `json:"short_link"`
	LongLink  string    `json:"long_link"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
