basePath: /
definitions:
  handler.DeleteLinkModel:
    description: Delete Link Model Url
    properties:
      url:
        type: string
    type: object
  handler.PasswordInput:
    description: Shorten link Model Password
    properties:
      password:
        type: string
    type: object
  handler.ShortenLinkModel:
    description: Shorten link Model Url, Custom_alias
    properties:
      custom_alias:
        type: string
      url:
        type: string
    type: object
  handler.User:
    description: User Model Username, email, Password
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  handler.UserInput:
    properties:
      identity:
        type: string
      password:
        type: string
    type: object
host: shortly-5p7d.onrender.com
info:
  contact:
    email: tinegagideon@outlook.com
    name: API Support
  description: This is a URL Shortener backend API built with Go.
  license:
    name: MIT License
    url: https://mit-license.org/
  termsOfService: http://swagger.io/terms/
  title: Shortly API
  version: 0.4.0
paths:
  /:
    get:
      description: Returns pong
      responses:
        "200":
          description: OK
      summary: Checks connectivity
  /{link}:
    get:
      description: Redirects to the original URL
      parameters:
      - description: Redirects to Original URL
        in: path
        name: link
        required: true
        type: string
      responses:
        "301":
          description: Moved Permanently
        "404":
          description: Not Found
      summary: Fetch a Original URL by Short URL
  /api/v1/auth/:
    post:
      description: Returns a JWT token
      parameters:
      - description: Login a user
        in: body
        name: Identity
        required: true
        schema:
          $ref: '#/definitions/handler.UserInput'
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Login user
  /api/v1/links/all:
    get:
      description: Returns all links
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Fetch all links
  /api/v1/links/shorten:
    delete:
      description: Returns a success message
      parameters:
      - description: Delete a Link
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/handler.DeleteLinkModel'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Delete url data by short url
      tags:
      - protected
    post:
      description: Returns a Short URL
      parameters:
      - description: Shorten a Link (custom alias is optional)
        in: body
        name: shorten_link
        required: true
        schema:
          $ref: '#/definitions/handler.ShortenLinkModel'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Insert an entry for a Short URL and Long URL
      tags:
      - protected
  /api/v1/links/userlinks:
    get:
      description: Returns all user links
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Fetch all user links
      tags:
      - protected
  /api/v1/users/:
    post:
      description: Returns a message
      parameters:
      - description: create a user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.User'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Create a user
  /api/v1/users/delete:
    delete:
      description: Returns a success message
      parameters:
      - description: Delete a user
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/handler.PasswordInput'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - protected
swagger: "2.0"
